# Generated by Django 6.0.4 on 2026-05-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id_campania', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'campania',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Combate',
            fields=[
                ('id_combate', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Activo', max_length=50)),
            ],
            options={
                'db_table': 'combate',
                'managed': False,
            },
        ),
    ]
