# Generated by Django 6.0.4 on 2026-05-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiradaDado',
            fields=[
                ('id_tirada', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_dado', models.CharField(choices=[('d4', 'd4'), ('d6', 'd6'), ('d8', 'd8'), ('d10', 'd10'), ('d12', 'd12'), ('d20', 'd20')], max_length=10)),
                ('resultado', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tirada_dado',
                'managed': False,
            },
        ),
    ]
